import { createClient } from '@supabase/supabase-js'
NEXT_PUBLIC_SUPABASE_URL=https://xwlrzgfuhfbckgvcmyoq.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3bHJ6Z2Z1aGZiY2tndmNteW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjM2MjQsImV4cCI6MjA3MTQ5OTYyNH0.AEglRqS4SCJ-BVhrb87KbLT6aYxQVxDcsYfYkLsf9q4

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
