import { useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import SEO from '@/components/SEO';
import PageSection from '@/components/PageSection';
import { CONTENT_RELEASE, MICRO_LESSONS, type MicroLesson } from '@/content/microLessons';

export default function Learn() {
  if (!import.meta.env.DEV) return <PageSection className="max-w-3xl"><SEO title="Lesson release status | VertexED" robots="noindex, follow" /><p className="text-sm text-primary mb-3">Curriculum release</p><h1 className="text-4xl font-semibold mb-5">Subject review comes first.</h1><p className="text-base leading-relaxed text-muted-foreground">Nine original MYP and Diploma Maths and Science lessons are in development. We will open them here after subject review and syllabus mapping. Draft teaching content is not included in public search.</p><Link className="inline-block mt-6 text-primary underline" to="/working-trace">Try the algebra checker</Link></PageSection>;
  return <DraftLessons />;
}
function DraftLessons() {
  const [params,setParams] = useSearchParams();
  const programme=params.get('programme') ?? 'All'; const subject=params.get('subject') ?? 'All';
  const filtered=MICRO_LESSONS.filter(l=>(programme==='All'||l.programme===programme)&&(subject==='All'||l.subject===subject));
  const selected=filtered.find(l=>l.id===params.get('topic')) ?? filtered[0];
  const change=(key:string,value:string)=>{const next=new URLSearchParams(params); if(value==='All')next.delete(key);else next.set(key,value);next.delete('topic');setParams(next);};
  return <PageSection className="max-w-6xl"><SEO title="Short lessons and focused practice | VertexED" description="Work through original maths and science examples, check your reasoning and try a transfer question." robots="noindex, follow" /><p className="text-sm text-primary mb-3">Learn / Practise / Return</p><h1 className="text-4xl md:text-5xl tracking-tight font-semibold mb-4">One idea, worked through.</h1><p className="text-base text-muted-foreground max-w-3xl leading-relaxed">Original draft lessons for MYP and Diploma study. Explanations, worked examples and one focused check. Subject review and exact syllabus mapping are pending; these are not official assessment materials.</p>
    <div className="flex flex-wrap gap-4 my-8">{[['programme',programme,['All','IB MYP','IB DP']],['subject',subject,['All','Mathematics','Physics','Chemistry','Biology']]].map(([key,value,options])=><label className="text-sm font-medium" key={key as string}>{key==='programme'?'Programme':'Subject'}<select className="block mt-2 min-h-11 rounded-lg border border-border bg-background text-foreground px-4 text-base" value={value as string} onChange={e=>change(key as string,e.target.value)}>{(options as string[]).map(o=><option key={o}>{o}</option>)}</select></label>)}</div>
    <div className="grid md:grid-cols-[250px_minmax(0,1fr)] gap-8"><nav aria-label="Micro-lessons" className="space-y-2">{filtered.map(l=><button key={l.id} type="button" aria-current={selected?.id===l.id?'page':undefined} className={`block w-full rounded-lg p-4 text-left border ${selected?.id===l.id?'border-primary bg-primary/5':'border-border bg-card'}`} onClick={()=>{const next=new URLSearchParams(params);next.set('topic',l.id);setParams(next);}}><span className="block text-xs text-muted-foreground mb-2">{l.programme} / {l.subject}</span><span className="text-base font-medium">{l.title}</span></button>)}</nav>{selected?<Lesson key={selected.id} lesson={selected}/>:<p>No lesson in this selection yet. Choose another subject or programme.</p>}</div>
  </PageSection>;
}
function Lesson({lesson}:{lesson:MicroLesson}) {
  const [choice,setChoice]=useState<number|null>(null);const [checked,setChecked]=useState(false);
  return <article className="rounded-xl border border-border bg-card p-6 md:p-9"><p className="text-sm text-primary">{lesson.topic}</p><h2 className="text-3xl tracking-tight font-semibold my-3">{lesson.title}</h2><p className="text-sm text-muted-foreground mb-7">Aim: {lesson.objective}</p><p className="text-base leading-relaxed">{lesson.explanation}</p><h3 className="text-lg font-semibold mt-8 mb-4">Follow the working</h3><ol className="space-y-3 border-l-2 border-primary pl-5">{lesson.worked.map((s,i)=><li className="text-base leading-relaxed" key={s}><span className="text-primary text-xs mr-3">0{i+1}</span>{s}</li>)}</ol><div className="mt-7 rounded-lg bg-primary/5 p-5"><h3 className="font-semibold mb-2">A mistake to watch for</h3><p className="text-base leading-relaxed">{lesson.misconception}</p></div><fieldset className="mt-8"><legend className="text-lg font-semibold mb-4">{lesson.question}</legend>{lesson.options.map((o,i)=><label className="flex items-center gap-3 border border-border rounded-lg p-4 mt-2 cursor-pointer" key={o}><input type="radio" name={lesson.id} checked={choice===i} onChange={()=>{setChoice(i);setChecked(false);}}/>{o}</label>)}</fieldset><button type="button" disabled={choice===null} className="mt-4 min-h-11 px-5 rounded-lg bg-primary text-primary-foreground font-medium disabled:opacity-50" onClick={()=>setChecked(true)}>Check my answer</button>{checked&&<div role="status" className="mt-5 p-5 border border-primary/30 rounded-lg"><h3 className="font-semibold">{choice===lesson.answer?'That answer agrees.':'Revisit the method.'}</h3><p className="mt-2 leading-relaxed">{lesson.feedback}</p><p className="mt-3 text-sm text-muted-foreground">One question checks this attempt. It does not establish mastery.</p></div>}<h3 className="text-lg font-semibold mt-8 mb-3">Now change the context</h3><p className="leading-relaxed">{lesson.transfer}</p>{lesson.subject==='Mathematics'&&<Link to="/working-trace" className="inline-block mt-5 text-primary underline">Check algebra with Working Trace</Link>}<footer className="mt-8 border-t border-border pt-5 text-sm text-muted-foreground leading-relaxed"><a href={lesson.source} target="_blank" rel="noopener noreferrer" className="underline">Concept reference: {lesson.sourceTitle}</a><p className="mt-2">{CONTENT_RELEASE.rights}</p><p>Release {CONTENT_RELEASE.version}. Draft; subject review pending.</p></footer></article>;
}
