export type ExamDrill = {
  id: string; programme: 'IB MYP' | 'IB DP' | 'AP'; subject: string; topic: string;
  focus: string; difficulty: 'foundation' | 'application' | 'extended'; minutes: number;
  prompt: string; checks: string[]; solution: string; transfer: string; source: string;
};

// Original editorial exercises, not past-paper extracts or official mark schemes.
export const EXAM_DRILLS: ExamDrill[] = [
  { id: 'myp-chem-collisions', programme: 'IB MYP', subject: 'Chemistry', topic: 'Reaction rates', focus: 'Criterion A practice: explain a mechanism', difficulty: 'application', minutes: 4,
    prompt: 'Equal masses of magnesium react with equal volumes and concentrations of acid at 20 °C and 35 °C. Explain why the warmer reaction initially produces gas faster. Give a connected explanation, not a list of keywords.',
    checks: ['Link temperature to particle kinetic energy.', 'Explain that a greater fraction of collisions exceeds activation energy.', 'Connect more successful collisions per second to a higher reaction rate.', 'Do not claim that heating lowers activation energy.'],
    solution: 'At the higher temperature, particles have greater average kinetic energy. A greater fraction of collisions has enough energy to react. Together with more frequent collisions, this increases successful collisions per second, producing gas faster. The activation energy of the same reaction is unchanged.',
    transfer: 'Now explain why a catalyst increases rate without raising temperature.', source: 'https://openstax.org/books/chemistry-2e/pages/12-5-collision-theory' },
  { id: 'myp-chem-design', programme: 'IB MYP', subject: 'Chemistry', topic: 'Reaction rates', focus: 'Criterion B practice: design a fair test', difficulty: 'application', minutes: 6,
    prompt: 'Design a school-laboratory investigation into how marble chip size affects the rate of reaction with dilute acid. State the independent variable, a measurable dependent variable, two controls and how you would improve reliability. Include a safety precaution. Follow teacher supervision, not this prompt as a practical protocol.',
    checks: ['Define chip-size categories or a measurable size range.', 'Measure gas volume at fixed time intervals.', 'Keep marble mass and acid concentration and volume constant.', 'Repeat each condition and compare results.', 'Use eye protection and a gas-collection arrangement that cannot dangerously pressurise.'],
    solution: 'Compare equal masses of differently sized marble chips with the same volume and concentration of dilute acid. Record gas volume against time using suitable school equipment. Repeat each condition and compare initial slopes, checking anomalies before averaging. Wear eye protection and follow the teacher-approved risk assessment.',
    transfer: 'Explain why comparing different masses would make the conclusion less secure.', source: 'https://ibo.org/programmes/middle-years-programme/curriculum/science/' },
  { id: 'myp-chem-data', programme: 'IB MYP', subject: 'Chemistry', topic: 'Reaction rates', focus: 'Criterion C practice: interpret evidence', difficulty: 'application', minutes: 5,
    prompt: 'A reaction produces 0, 18, 30 and 36 cm³ of gas at 0, 10, 20 and 30 seconds. Calculate its average rate over the first 10 seconds and final 10 seconds. Explain the change and one limitation of using only these readings.',
    checks: ['First interval: 1.8 cm³/s.', 'Final interval: 0.6 cm³/s.', 'Explain a plausible decrease in reactant concentration as reactants are used.', 'Distinguish an interval average from an instantaneous rate.'],
    solution: 'The first rate is (18 − 0)/10 = 1.8 cm³/s. The final rate is (36 − 30)/10 = 0.6 cm³/s. The slowing is consistent with reactants being used up. These are interval averages; more frequent readings are needed to describe the changing rate more precisely. The data alone does not establish a unique reaction mechanism.',
    transfer: 'Calculate the mean rate over all 30 seconds, then explain why it hides the early change.', source: 'https://openstax.org/books/chemistry-2e/pages/12-1-chemical-reaction-rates' },
  { id: 'myp-chem-impact', programme: 'IB MYP', subject: 'Chemistry', topic: 'Environmental chemistry', focus: 'Criterion D practice: weigh an application', difficulty: 'extended', minutes: 8,
    prompt: 'A town proposes a catalytic process to reduce one industrial air pollutant. Write a short recommendation that explains how a catalyst works, considers an environmental benefit and an economic limitation, and identifies evidence needed before a decision. Do not invent statistics.',
    checks: ['Explain a lower-activation-energy pathway.', 'Connect pollutant reduction to a specified possible benefit.', 'Discuss catalyst cost, lifetime or disposal as a limitation.', 'Weigh both sides in a qualified recommendation.', 'Identify a credible source or measurement needed to check the claim.'],
    solution: 'A catalyst offers an alternative pathway with lower activation energy. If the process converts the target pollutant into less harmful products, it may improve local air quality. Purchase, replacement and disposal costs must also be considered. A trial is justified if measured emissions fall and lifecycle costs are acceptable. Compare verified inlet and outlet emissions and examine by-products before recommending full installation.',
    transfer: 'Replace the economic limitation with an ethical or social implication, and explain who is affected.', source: 'https://openstax.org/books/chemistry-2e/pages/12-7-catalysis' },
  { id: 'myp-bio-osmosis', programme: 'IB MYP', subject: 'Biology', topic: 'Cell transport', focus: 'Criterion A practice: connect direction and consequence', difficulty: 'foundation', minutes: 4,
    prompt: 'A plant cell is placed in a concentrated salt solution. Explain the initial net movement of water and a possible effect on the cell.',
    checks: ['Name osmosis and a partially permeable membrane.', 'State net water movement out of the cell.', 'Relate movement to the water-potential difference.', 'Explain loss of turgor; sufficiently severe loss can cause plasmolysis.'],
    solution: 'Water moves out by osmosis across the partially permeable cell membrane toward the lower water potential outside. The vacuole loses water and turgor falls. With sufficient water loss the membrane can pull away from the cell wall. The wall itself does not shrink in the same way.',
    transfer: 'Predict the change when the cell is returned to fresh water and justify the direction.', source: 'https://openstax.org/books/biology-2e/pages/5-2-passive-transport' },
  { id: 'myp-physics-energy', programme: 'IB MYP', subject: 'Physics', topic: 'Energy', focus: 'Criterion A practice: calculate and interpret', difficulty: 'foundation', minutes: 4,
    prompt: 'A device receives 500 J of energy and transfers 350 J usefully. Calculate efficiency, account for the remaining energy and explain why it is misleading to say that energy was destroyed.',
    checks: ['Use useful output divided by total input.', 'Calculate 70%.', 'Identify 150 J transferred to less useful stores or pathways.', 'Apply conservation of energy.'],
    solution: 'Efficiency is 350/500 × 100 = 70%. The remaining 150 J is transferred through less useful pathways, such as heating the surroundings. Total energy is conserved even when it becomes less useful for the intended purpose.',
    transfer: 'A second device supplies the same useful output at 80% efficiency. Find its required input.', source: 'https://openstax.org/books/physics/pages/9-2-mechanical-energy-and-conservation-of-energy' },
  { id: 'dp-maths-fractions', programme: 'IB DP', subject: 'Mathematics', topic: 'Partial fractions', focus: 'Prerequisite repair: algebra before integration', difficulty: 'foundation', minutes: 6,
    prompt: 'Without a calculator, express (3x + 5)/((x + 1)(x + 2)) as partial fractions. State the excluded values. Then integrate the expression.',
    checks: ['Set A/(x + 1) + B/(x + 2).', 'Derive A + B = 3 and 2A + B = 5.', 'Find A = 2 and B = 1; exclude x = −1, −2.', 'Integrate to 2 ln|x + 1| + ln|x + 2| + C on an interval avoiding the excluded values.'],
    solution: 'Equating numerators gives 3x + 5 = A(x + 2) + B(x + 1). Therefore A = 2, B = 1. The integral is 2 ln|x + 1| + ln|x + 2| + C on each interval where the expression is defined. Differentiating and recombining verifies the result.',
    transfer: 'Repeat with numerator 5x + 7. Repair coefficient matching before attempting a longer integration question.', source: 'https://openstax.org/books/calculus-volume-2/pages/3-4-partial-fractions' },
  { id: 'dp-maths-stationary-points', programme: 'IB DP', subject: 'Mathematics', topic: 'Differentiation', focus: 'Calculus practice: classify stationary points', difficulty: 'application', minutes: 6,
    prompt: 'For f(x) = x³ − 3x² − 9x + 5, find the stationary points and classify each as a local maximum or local minimum. Show the derivative evidence you use for the classification.',
    checks: ['Differentiate to f′(x) = 3x² − 6x − 9 = 3(x − 3)(x + 1).', 'Find stationary x-values −1 and 3.', 'Evaluate f(−1) = 10 and f(3) = −22.', 'Use f″(x) = 6x − 6 or a derivative sign change: (−1, 10) is a local maximum and (3, −22) is a local minimum.'],
    solution: 'Setting f′(x) = 3(x − 3)(x + 1) equal to zero gives x = −1 and x = 3. The corresponding values are f(−1) = 10 and f(3) = −22. Since f″(−1) = −12, the first is a local maximum; since f″(3) = 12, the second is a local minimum.',
    transfer: 'Explain what would and would not change in the stationary-point classification if 7 were added to f(x).', source: 'https://openstax.org/books/calculus-volume-1/pages/4-3-maxima-and-minima' },
  { id: 'dp-maths-conditional-probability', programme: 'IB DP', subject: 'Mathematics', topic: 'Probability', focus: 'Probability practice: test independence from evidence', difficulty: 'application', minutes: 5,
    prompt: 'Events A and B have P(A) = 0.6, P(B) = 0.5 and P(A ∩ B) = 0.3. Find P(A | B), decide whether A and B are independent, and justify the decision using probabilities rather than a diagram alone.',
    checks: ['Use P(A | B) = P(A ∩ B) / P(B).', 'Calculate P(A | B) = 0.3 / 0.5 = 0.6.', 'Compare P(A | B) with P(A), or compare P(A ∩ B) with P(A)P(B).', 'Conclude that A and B are independent for these stated probabilities.'],
    solution: 'P(A | B) = 0.3/0.5 = 0.6, which equals P(A). Equivalently, P(A)P(B) = 0.6 × 0.5 = 0.3 = P(A ∩ B). Either equality verifies independence under the stated probabilities.',
    transfer: 'Keep P(A) and P(B) unchanged but change P(A ∩ B) to 0.2. Recalculate P(A | B) and explain why independence no longer holds.', source: 'https://openstax.org/books/introductory-statistics-2e/pages/3-2-independent-and-mutually-exclusive-events' },
  { id: 'ap-calc-accumulation', programme: 'AP', subject: 'Mathematics', topic: 'Accumulation', focus: 'Calculus practice: interpret a definite integral', difficulty: 'application', minutes: 5,
    prompt: 'Water enters a tank at r(t) = 2t + 3 litres per minute for 0 ≤ t ≤ 4. The tank initially holds 10 litres and has no outflow. Find the volume at t = 4 and explain what your integral represents.',
    checks: ['Integrate the rate from 0 to 4.', 'Evaluate [t² + 3t] from 0 to 4 as 28 litres.', 'Add initial volume to obtain 38 litres.', 'Interpret accumulated change and include units.'],
    solution: 'The definite integral of the inflow rate gives the added volume: 16 + 12 = 28 litres. Adding the initial 10 litres gives 38 litres. The integral is a change, not the final amount by itself.',
    transfer: 'If an outlet removes 2 litres per minute throughout, find the final volume using the net rate.', source: 'https://openstax.org/books/calculus-volume-1/pages/5-4-integration-formulas-and-the-net-change-theorem' },
  { id: 'dp-physics-net-force', programme: 'IB DP', subject: 'Physics', topic: 'Forces', focus: 'Mechanics practice: resolve net force', difficulty: 'foundation', minutes: 5,
    prompt: 'A 1200 kg car accelerates in a straight line at 2.5 m/s². Resistive forces total 800 N opposite the motion. Find the resultant force and then the driving force. State the direction of each force quantity you calculate.',
    checks: ['Use resultant force F = ma.', 'Calculate the forward resultant as 3000 N.', 'Recognize that the driving force must also overcome the 800 N resistance.', 'Calculate a driving force of 3800 N forward and distinguish it from the resultant.'],
    solution: 'The resultant force is ma = 1200 × 2.5 = 3000 N forward. If the driving force is D, then D − 800 = 3000, so D = 3800 N forward. The 3000 N value is the net force after resistance is included.',
    transfer: 'If the same driving force acts while resistance rises to 1400 N, calculate the new acceleration.', source: 'https://openstax.org/books/physics/pages/4-3-newtons-second-law-of-motion' },
  { id: 'dp-physics-circular-motion', programme: 'IB DP', subject: 'Physics', topic: 'Circular motion', focus: 'Mechanics practice: connect acceleration and force', difficulty: 'application', minutes: 5,
    prompt: 'A 0.50 kg object moves at constant speed 4.0 m/s in a horizontal circle of radius 2.0 m. Find its centripetal acceleration and the magnitude of the resultant force. State the direction of the acceleration and force.',
    checks: ['Use a = v²/r.', 'Calculate 8.0 m/s².', 'Use F = ma to obtain 4.0 N.', 'State that both acceleration and resultant force point toward the centre even though speed is constant.'],
    solution: 'The centripetal acceleration is v²/r = 16/2 = 8.0 m/s². The resultant force is ma = 0.50 × 8.0 = 4.0 N. Both vectors point radially inward toward the centre of the circle.',
    transfer: 'Keep the radius fixed and double the speed. Explain how the centripetal acceleration and force change.', source: 'https://openstax.org/books/physics/pages/6-2-uniform-circular-motion' },
  { id: 'dp-physics-energy', programme: 'IB DP', subject: 'Physics', topic: 'Energy', focus: 'Mechanics practice: track energy through a system', difficulty: 'application', minutes: 6,
    prompt: 'A 2.0 kg object is released from rest 5.0 m above the ground. Ignore air resistance and use g = 9.8 m/s². Find its gravitational potential energy relative to the ground and its speed immediately before impact. Explain the energy transfer used.',
    checks: ['Calculate mgh = 98 J.', 'Set the lost gravitational potential energy equal to gained kinetic energy.', 'Use ½mv² = 98 J.', 'Obtain v = √98 ≈ 9.9 m/s and state the no-dissipation assumption.'],
    solution: 'Initially the object has mgh = 2.0 × 9.8 × 5.0 = 98 J of gravitational potential energy relative to the ground. With air resistance neglected, this becomes kinetic energy: ½(2.0)v² = 98, so v² = 98 and v ≈ 9.9 m/s.',
    transfer: 'If 20 J were transferred to the surroundings before impact, calculate the new kinetic energy and impact speed.', source: 'https://openstax.org/books/physics/pages/9-2-mechanical-energy-and-conservation-of-energy' },
  { id: 'dp-cs-bitwise-and', programme: 'IB DP', subject: 'Computer Science', topic: 'Binary and bitwise logic', focus: 'Representation practice: trace a bitwise operation', difficulty: 'foundation', minutes: 4,
    prompt: 'Write decimal 13 and decimal 10 as four-bit binary values. Apply bitwise AND to the two bit patterns, then give the result in both binary and decimal. Explain the rule used for each output bit.',
    checks: ['Convert 13 to 1101 and 10 to 1010.', 'Apply AND position by position.', 'Obtain 1000.', 'Convert 1000₂ to 8 and explain that an AND output bit is 1 only when both input bits are 1.'],
    solution: '13 is 1101₂ and 10 is 1010₂. Comparing each position with AND gives 1000₂, which is decimal 8. Only the leftmost compared pair contains 1 and 1; every other position contains at least one 0.',
    transfer: 'Using the same inputs, predict the four-bit result of bitwise OR before calculating it.', source: 'https://ibo.org/programmes/diploma-programme/curriculum/sciences/computer-science/' },
  { id: 'dp-cs-loop-trace', programme: 'IB DP', subject: 'Computer Science', topic: 'Algorithms', focus: 'Algorithm practice: trace iteration state', difficulty: 'application', minutes: 5,
    prompt: 'Trace this pseudocode: total ← 0; FOR i ← 1 TO 4: total ← total + 2 × i; END FOR. Give the value of total after each iteration and the final output. Then state how many loop-body executions occur.',
    checks: ['Track i in order as 1, 2, 3, 4.', 'Record totals 2, 6, 12, 20.', 'Give final output 20.', 'State that the loop body executes four times and distinguish iteration count from the final total.'],
    solution: 'Starting from 0, the loop adds 2, then 4, then 6, then 8. The running totals are 2, 6, 12 and 20. The final output is 20, and the loop body executes exactly four times.',
    transfer: 'Generalize the final total for a loop that runs i from 1 through n and adds 2i each time.', source: 'https://ibo.org/programmes/diploma-programme/curriculum/sciences/computer-science/' },
  { id: 'dp-cs-boolean-expression', programme: 'IB DP', subject: 'Computer Science', topic: 'Boolean logic', focus: 'Logic practice: evaluate a compound condition', difficulty: 'application', minutes: 4,
    prompt: 'Let A = true, B = false and C = false. Evaluate (A AND NOT B) OR C. Show the intermediate value of NOT B and of A AND NOT B before giving the final result.',
    checks: ['Evaluate NOT B as true.', 'Evaluate A AND NOT B as true.', 'Evaluate true OR false as true.', 'Preserve the stated grouping rather than changing the expression order.'],
    solution: 'Because B is false, NOT B is true. A is also true, so A AND NOT B is true. Finally, true OR C is true OR false, which is true.',
    transfer: 'Keep A and B unchanged. What value of C, if any, would make the full expression false? Explain.', source: 'https://ibo.org/programmes/diploma-programme/curriculum/sciences/computer-science/' },

  { id: 'dp-maths-complex-polar', programme: 'IB DP', subject: 'Mathematics', topic: 'Complex numbers', focus: 'AA HL practice: move between Cartesian and polar form', difficulty: 'application', minutes: 6,
    prompt: 'Let z = 1 + √3 i. Find |z| and an argument of z, then write z in the form r(cos θ + i sin θ). Use your polar form to find z² exactly.',
    checks: ['Calculate |z| = √(1 + 3) = 2.', 'Recognize that z lies in quadrant I with argument π/3.', 'Write z = 2(cos(π/3) + i sin(π/3)).', 'Apply de Moivre to obtain z² = 4(cos(2π/3) + i sin(2π/3)) = −2 + 2√3 i.'],
    solution: 'The modulus is 2 and the principal argument is π/3, so z = 2(cos(π/3) + i sin(π/3)). Squaring doubles the argument and squares the modulus: z² = 4(cos(2π/3) + i sin(2π/3)) = −2 + 2√3 i.',
    transfer: 'Use the same polar representation to find z³ without first expanding z²z in Cartesian form.', source: 'https://openstax.org/books/precalculus-2e/pages/3-5-complex-numbers' },
  { id: 'dp-maths-induction-sum', programme: 'IB DP', subject: 'Mathematics', topic: 'Proof by induction', focus: 'AA HL practice: structure an induction proof', difficulty: 'extended', minutes: 8,
    prompt: 'Prove by mathematical induction that 1 + 3 + 5 + … + (2n − 1) = n² for every positive integer n. Make the base case, induction hypothesis, and induction step explicit.',
    checks: ['Verify n = 1.', 'Assume the statement for n = k.', 'Add the next odd term 2(k + 1) − 1 = 2k + 1.', 'Show k² + 2k + 1 = (k + 1)² and close the induction argument.'],
    solution: 'For n = 1, both sides equal 1. Assume 1 + 3 + … + (2k − 1) = k². Then the sum through the next odd term is k² + (2k + 1) = (k + 1)². Therefore the result holds for k + 1, so by induction it holds for every positive integer n.',
    transfer: 'Adapt the structure to prove 2 + 4 + … + 2n = n(n + 1).', source: 'https://openstax.org/books/precalculus-2e/pages/9-4-use-mathematical-induction' },
  { id: 'dp-maths-binomial-term', programme: 'IB DP', subject: 'Mathematics', topic: 'Binomial theorem', focus: 'AA HL practice: isolate a target term', difficulty: 'application', minutes: 6,
    prompt: 'Find the coefficient of x³ in the expansion of (2 + x)⁶. State the general term you use and identify the value of the term index that produces x³.',
    checks: ['Use C(6,r) 2^(6−r) x^r.', 'Set r = 3 for the x³ term.', 'Calculate C(6,3) = 20.', 'Calculate 20 × 2³ = 160.'],
    solution: 'The general term is C(6,r)2^(6−r)x^r. The x³ term occurs at r = 3, giving coefficient C(6,3)2³ = 20 × 8 = 160.',
    transfer: 'Find the coefficient of x⁴ in (3 − 2x)⁶, paying attention to the sign.', source: 'https://openstax.org/books/precalculus-2e/pages/11-6-binomial-theorem' },
  { id: 'dp-physics-projectile', programme: 'IB DP', subject: 'Physics', topic: 'Projectile motion', focus: 'Mechanics practice: separate horizontal and vertical motion', difficulty: 'application', minutes: 7,
    prompt: 'A ball is launched horizontally at 8.0 m/s from a 20 m high platform. Ignore air resistance and use g = 9.8 m/s². Find the time to reach the ground and the horizontal distance travelled.',
    checks: ['Use vertical motion with initial vertical velocity zero.', 'Solve 20 = ½gt² to get t ≈ 2.02 s.', 'Keep horizontal velocity constant at 8.0 m/s.', 'Calculate horizontal distance ≈ 16.2 m.'],
    solution: 'Vertically, 20 = 0.5(9.8)t², so t = √(40/9.8) ≈ 2.02 s. Horizontally the velocity stays 8.0 m/s, so the distance is 8.0 × 2.02 ≈ 16.2 m.',
    transfer: 'If the launch speed doubles but the height is unchanged, explain what happens to the flight time and horizontal range.', source: 'https://openstax.org/books/physics/pages/5-3-projectile-motion' },
  { id: 'dp-physics-momentum', programme: 'IB DP', subject: 'Physics', topic: 'Momentum', focus: 'Mechanics practice: apply momentum conservation', difficulty: 'application', minutes: 6,
    prompt: 'A 2.0 kg cart moving at 4.0 m/s collides with a 3.0 kg cart at rest and they stick together. Find their common velocity immediately after the collision and state what happens to kinetic energy.',
    checks: ['Use conservation of momentum for the two-cart system.', 'Calculate initial momentum as 8.0 kg·m/s.', 'Divide by combined mass 5.0 kg to obtain 1.6 m/s.', 'State that kinetic energy is not conserved in a perfectly inelastic collision.'],
    solution: 'Initial momentum is (2.0)(4.0) = 8.0 kg·m/s. After sticking, total mass is 5.0 kg, so v = 8.0/5.0 = 1.6 m/s in the original direction. Momentum is conserved for the isolated system, but kinetic energy decreases.',
    transfer: 'Calculate the initial and final kinetic energies and quantify the energy transferred to other stores.', source: 'https://openstax.org/books/physics/pages/8-3-elastic-and-inelastic-collisions' },
  { id: 'dp-physics-circuit-power', programme: 'IB DP', subject: 'Physics', topic: 'Electric circuits', focus: 'Electricity practice: connect resistance, current and power', difficulty: 'application', minutes: 6,
    prompt: 'A 12 V supply is connected across a 6.0 Ω resistor. Find the current and the power dissipated by the resistor. Then state the energy transferred in 30 s.',
    checks: ['Use I = V/R to obtain 2.0 A.', 'Use P = VI or V²/R to obtain 24 W.', 'Use E = Pt.', 'Calculate 720 J in 30 s.'],
    solution: 'The current is 12/6.0 = 2.0 A. The power is VI = 12 × 2.0 = 24 W. In 30 s, the transferred energy is Pt = 24 × 30 = 720 J.',
    transfer: 'If the same resistor is connected to 6 V instead, compare the new power with the original power.', source: 'https://openstax.org/books/physics/pages/19-4-electric-power' },
  { id: 'dp-cs-hex-conversion', programme: 'IB DP', subject: 'Computer Science', topic: 'Number representation', focus: 'Representation practice: convert binary, decimal and hexadecimal', difficulty: 'foundation', minutes: 5,
    prompt: 'Convert binary 10110110₂ to hexadecimal and decimal. Show how you group the binary digits for the hexadecimal conversion.',
    checks: ['Group as 1011 0110.', 'Convert 1011 to B and 0110 to 6.', 'Obtain B6₁₆.', 'Calculate decimal 128 + 32 + 16 + 4 + 2 = 182.'],
    solution: 'Grouping into nibbles gives 1011 0110, which maps to B6₁₆. In decimal the set bit values sum to 128 + 32 + 16 + 4 + 2 = 182.',
    transfer: 'Convert 3F₁₆ to eight-bit binary and decimal.', source: 'https://ibo.org/programmes/diploma-programme/curriculum/sciences/computer-science/' },
  { id: 'dp-cs-kmap', programme: 'IB DP', subject: 'Computer Science', topic: 'Boolean simplification', focus: 'Logic practice: simplify from a small Karnaugh map', difficulty: 'extended', minutes: 7,
    prompt: 'A two-variable function F(A,B) is 1 for input pairs 01 and 11, and 0 for 00 and 10. Determine the simplest Boolean expression for F and justify it from the pattern of outputs.',
    checks: ['Notice that both rows with B = 1 produce F = 1.', 'Notice that changing A does not change the output when B is fixed.', 'Conclude that A is eliminated.', 'State F = B.'],
    solution: 'The output is 1 exactly when B is 1, regardless of A. The two adjacent 1-cells therefore eliminate A, leaving the simplified expression F = B.',
    transfer: 'If the 1-cells instead occur at 10 and 11, determine the simplified expression.', source: 'https://ibo.org/programmes/diploma-programme/curriculum/sciences/computer-science/' },
  { id: 'dp-cs-stack-queue', programme: 'IB DP', subject: 'Computer Science', topic: 'Data structures', focus: 'Data-structure practice: distinguish stack and queue behavior', difficulty: 'application', minutes: 5,
    prompt: 'Items A, B and C are inserted in that order. Give the removal order if the structure is a stack, and then if it is a queue. Name the access rule used by each structure.',
    checks: ['For a stack, remove C, then B, then A.', 'Name the stack rule LIFO.', 'For a queue, remove A, then B, then C.', 'Name the queue rule FIFO.'],
    solution: 'A stack removes the most recently inserted item first, so the order is C, B, A: last in, first out (LIFO). A queue removes the earliest inserted item first, so the order is A, B, C: first in, first out (FIFO).',
    transfer: 'Give one computing scenario where a stack is appropriate and one where a queue is appropriate.', source: 'https://ibo.org/programmes/diploma-programme/curriculum/sciences/computer-science/' },

];