export type MicroLesson = {
  id: string; programme: 'IB MYP' | 'IB DP'; subject: string; topic: string; title: string;
  objective: string; explanation: string; worked: string[]; misconception: string;
  question: string; options: string[]; answer: number; feedback: string; transfer: string;
  source: string; sourceTitle: string;
};
export const CONTENT_RELEASE = { version: '2026-09-19.1', author: 'VertexED', rights: 'Original VertexED explanations and exercises. Linked references retain their own licences.', reviewStatus: 'draft', reviewer: null, reviewedAt: null, curriculumVersion: 'Programme orientation only; exact syllabus mapping pending review' } as const;
export const MICRO_LESSONS: MicroLesson[] = [
  {id:'algebra',programme:'IB MYP',subject:'Mathematics',topic:'Algebra',title:'Keep an equation balanced',objective:'Preserve the solution when expanding and rearranging a linear equation.',explanation:'An equation states that two quantities are equal. Expand every term inside a bracket. Then apply the same operation to both sides to isolate the unknown.',worked:['3(x + 2) = 21','3x + 6 = 21','3x = 15','x = 5','Check: 3(5 + 2) = 21.'],misconception:'Multiplying only the first term gives 3x + 2. The factor outside applies to both terms.',question:'Solve 4(x + 2) = 28. What is x?',options:['3','5','6.5','9'],answer:1,feedback:'Expand to 4x + 8 = 28. Subtract 8, then divide by 4: x = 5.',transfer:'Write and solve an equation for three identical notebooks and a £4 pen costing £19 altogether.',source:'https://openstax.org/books/elementary-algebra-2e/pages/2-2-solve-equations-using-the-division-and-multiplication-properties-of-equality',sourceTitle:'OpenStax: properties of equality'},
  {id:'gradient',programme:'IB MYP',subject:'Mathematics',topic:'Linear functions',title:'Read a rate from two points',objective:'Calculate gradient and interpret it with units.',explanation:'Gradient compares a change in the vertical quantity with the corresponding change in the horizontal quantity. Use the same point order in both differences. A straight line has one constant gradient.',worked:['A tank contains 8 litres at 2 minutes and 20 litres at 5 minutes.','Change in volume = 20 − 8 = 12 litres.','Change in time = 5 − 2 = 3 minutes.','Gradient = 12/3 = 4 litres per minute.'],misconception:'20/5 ignores the other point. A rate is a ratio of changes, not necessarily a ratio of coordinates.',question:'A line passes through (1, 7) and (4, 13). Its gradient is:',options:['2','3','6','13/4'],answer:0,feedback:'The vertical change is 6 and the horizontal change is 3. The gradient is 2.',transfer:'Create two different linear rules with gradient 2. Explain how their intercepts change the context.',source:'https://openstax.org/books/elementary-algebra-2e/pages/4-4-understand-slope-of-a-line',sourceTitle:'OpenStax: slope of a line'},
  {id:'force',programme:'IB MYP',subject:'Physics',topic:'Forces',title:'Use the resultant force',objective:'Connect a resultant force to acceleration for constant mass.',explanation:'For a constant mass, acceleration depends on the resultant force. Forces in opposite directions subtract. Choose a positive direction and keep signs consistent. A zero resultant permits constant velocity, including rest.',worked:['A 4 kg trolley is pushed right with 18 N while resistance is 6 N left.','Resultant force = 18 − 6 = 12 N right.','a = F/m = 12/4 = 3 m/s² right.'],misconception:'Using 18 N alone ignores the opposing force. Constant speed also needs an unchanged direction before you can infer zero acceleration.',question:'A 2 kg object has a resultant force of 10 N. What is its acceleration?',options:['20 m/s²','5 m/s²','0.2 m/s²','12 m/s²'],answer:1,feedback:'Divide the resultant force by the mass: 10/2 = 5 m/s², in the force direction.',transfer:'Describe a moving object with zero resultant force. State the assumptions about its direction.',source:'https://openstax.org/books/physics/pages/4-3-newtons-second-law-of-motion',sourceTitle:'OpenStax: Newton’s second law'},
  {id:'energy',programme:'IB MYP',subject:'Physics',topic:'Energy',title:'Account for the whole transfer',objective:'Calculate efficiency and apply conservation of energy.',explanation:'Efficiency compares useful output with total input. Energy transferred by unwanted pathways is still part of the energy account. It is less useful for the intended task, rather than destroyed.',worked:['A motor receives 800 J and transfers 600 J usefully.','Efficiency = 600/800 × 100 = 75%.','The remaining 200 J is transferred through other pathways.'],misconception:'Subtracting input from output is not an efficiency calculation. An efficiency above 100% signals an inconsistent energy account.',question:'A lamp transfers 12 J as useful light from 60 J of electrical input. Its efficiency is:',options:['5%','20%','48%','72%'],answer:1,feedback:'Useful output divided by input is 12/60 = 0.20, or 20%.',transfer:'A device needs 240 J of useful output at 80% efficiency. Find the input and explain where the difference goes.',source:'https://openstax.org/books/physics/pages/9-2-mechanical-energy-and-conservation-of-energy',sourceTitle:'OpenStax: conservation of energy'},
  {id:'osmosis',programme:'IB MYP',subject:'Biology',topic:'Cell transport',title:'Explain the direction of water movement',objective:'Connect water potential, membrane permeability and a cell response.',explanation:'Osmosis is the net movement of water across a selectively permeable membrane toward lower water potential. In a concentrated external salt solution, a plant cell can lose water and turgor. The rigid wall and cell membrane behave differently.',worked:['External solution has lower water potential than the cell.','Water moves out across the membrane.','The vacuole loses water and turgor decreases.','Sufficient water loss can pull the membrane away from the wall.'],misconception:'Saying that salt pulls the cell wall inward confuses the wall with the membrane and does not explain net water movement.',question:'What initially happens when a plant cell enters a sufficiently concentrated salt solution?',options:['Water enters by active transport','Water leaves by osmosis','The cell wall dissolves','Water stops moving'],answer:1,feedback:'The lower external water potential leads to net water movement out, reducing turgor.',transfer:'Predict what may happen when the cell is returned to fresh water. Explain both direction and mechanism.',source:'https://openstax.org/books/biology-2e/pages/5-2-passive-transport',sourceTitle:'OpenStax: passive transport'},
  {id:'derivative',programme:'IB DP',subject:'Mathematics',topic:'Differentiation',title:'Differentiate, then interpret',objective:'Use the power rule on a polynomial and interpret an instantaneous rate.',explanation:'Differentiation gives a local rate of change. For a polynomial term axⁿ, the derivative is anxⁿ⁻¹. Differentiate each term; constants have derivative zero. Then substitute the point where the rate is needed.',worked:['s(t) = 2t³ − 3t + 4 metres.','v(t) = 6t² − 3 metres per second.','At t = 2 s, v = 6(4) − 3 = 21 m/s.'],misconception:'Substituting before differentiating turns the expression into a number and loses how it varies.',question:'If f(x) = 3x² + 2x − 5, what is f′(2)?',options:['11','12','14','19'],answer:2,feedback:'f′(x) = 6x + 2, so f′(2) = 14.',transfer:'Find where f(x) = x² − 6x has a horizontal tangent. Explain what horizontal means for the derivative.',source:'https://openstax.org/books/calculus-volume-1/pages/3-3-differentiation-rules',sourceTitle:'OpenStax: differentiation rules'},
  {id:'accumulation',programme:'IB DP',subject:'Mathematics',topic:'Integration',title:'Separate change from final amount',objective:'Interpret a definite integral as accumulated change.',explanation:'Integrating a rate over an interval gives the signed change in its quantity. Add the initial amount to obtain the final amount. Check that the units of rate multiplied by time give the quantity you want.',worked:['A tank starts with 7 litres. Inflow is r(t) = 2t + 1 L/min for 0 ≤ t ≤ 3.','Added volume = [t² + t] from 0 to 3 = 12 litres.','Final volume = 7 + 12 = 19 litres.'],misconception:'The definite integral gives the change. It equals the final amount only when the initial amount is zero and all flows are accounted for.',question:'A tank starts with 5 L and gains 3 L/min for 4 minutes. With no outflow, the final amount is:',options:['7 L','12 L','17 L','20 L'],answer:2,feedback:'The added amount is 3 × 4 = 12 L. Add the initial 5 L to obtain 17 L.',transfer:'Include an outflow of 1 L/min and calculate the final amount using the net rate.',source:'https://openstax.org/books/calculus-volume-1/pages/5-4-integration-formulas-and-the-net-change-theorem',sourceTitle:'OpenStax: net change theorem'},
  {id:'moles',programme:'IB DP',subject:'Chemistry',topic:'Amount of substance',title:'Connect mass to amount',objective:'Use molar mass with consistent units to calculate amount of substance.',explanation:'Molar mass relates the mass of a sample to its amount in moles. Use n = m/M. When mass is in grams, use molar mass in grams per mole. A reaction equation then gives mole ratios, rather than direct mass ratios.',worked:['A sample has mass 9.0 g and molar mass 18.0 g/mol.','n = 9.0/18.0 = 0.50 mol.','The gram units cancel, leaving moles.'],misconception:'A coefficient in a balanced equation compares numbers of entities or moles. Different substances generally have different molar masses.',question:'How many moles are in 11.0 g of a substance with molar mass 44.0 g/mol?',options:['0.25 mol','4.0 mol','33.0 mol','484 mol'],answer:0,feedback:'n = 11.0/44.0 = 0.250 mol to three significant figures.',transfer:'For 2H₂ + O₂ → 2H₂O, state the amount of oxygen needed for 0.60 mol of hydrogen, assuming complete reaction.',source:'https://openstax.org/books/chemistry-2e/pages/3-1-formula-mass-and-the-mole-concept',sourceTitle:'OpenStax: the mole concept'},
  {id:'dimensions',programme:'IB DP',subject:'Physics',topic:'Measurement',title:'Check the dimensions first',objective:'Use SI dimensions to reject an inconsistent relationship.',explanation:'Terms that are added must have the same dimensions. Both sides of an equation must also agree dimensionally. Agreement is necessary, but it cannot prove that a model, numerical factor or unit conversion is correct.',worked:['Force = mass × acceleration.','Units: kg × m/s² = kg m s⁻² = N.','Energy = force × distance.','Units: N m = kg m² s⁻² = J.'],misconception:'Dimensionally consistent does not mean physically correct. F = 2ma has consistent dimensions but is not the general second-law equation for a constant-mass object.',question:'Which expression has the dimensions of energy?',options:['mass × speed','mass × speed²','force / distance','distance / time'],answer:1,feedback:'kg × (m/s)² = kg m² s⁻², the dimensions of energy.',transfer:'Show why adding a distance directly to a speed is dimensionally inconsistent.',source:'https://openstax.org/books/physics/pages/4-3-newtons-second-law-of-motion',sourceTitle:'OpenStax: force, mass and acceleration'},
];

// Null mappings are intentional: programme labels are not verified syllabus alignment.
export const MICRO_LESSON_REGISTRY = MICRO_LESSONS.map(lesson => ({
  id: lesson.id,
  board: 'IB', programme: lesson.programme, subject: lesson.subject, topic: lesson.topic,
  year: lesson.programme === 'IB MYP' ? 'MYP 5 candidate' : 'DP candidate',
  syllabusVersion: null, syllabusObjectiveId: null, level: null,
  objective: lesson.objective, commandTerm: null, difficulty: 'foundation',
  questionTypes: ['multiple-choice', 'open-transfer'], markSchemeSkill: null,
  source: lesson.source, sourceTitle: lesson.sourceTitle, sourceRelationship: 'concept-reference-not-official-syllabus',
  authorship: 'VertexED-authored-teaching', author: CONTENT_RELEASE.author,
  rights: CONTENT_RELEASE.rights, version: CONTENT_RELEASE.version,
  reviewStatus: CONTENT_RELEASE.reviewStatus, reviewer: CONTENT_RELEASE.reviewer,
  reviewedAt: CONTENT_RELEASE.reviewedAt, publicApproved: false,
}));
