#!/usr/bin/env node

import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const viteCli = resolve('node_modules/vite/bin/vite.js');
const buildRevisionModule = resolve('api/_generated/build-revision.js');
const neutralBuildRevision = [
  '// Generated by scripts/generate-build-revision.mjs. Do not edit by hand.',
  'export const BUILD_REVISION = null;',
  '',
].join('\n');

let result;
try {
  result = spawnSync(process.execPath, [viteCli, 'build'], {
    env: { ...process.env, ROLLUP_SKIP_NODEJS_NATIVE: 'true' },
    stdio: 'inherit',
  });
} finally {
  // Vercel packages the serverless function after this command exits, so its
  // source tree must retain the immutable stamp. Local and CI builds only need
  // the stamp while Vite packages the artifact; restore repository neutrality
  // so later tests cannot mistake a previous build for deployment identity.
  if (process.env.VERCEL !== '1') {
    writeFileSync(buildRevisionModule, neutralBuildRevision, 'utf8');
  }
}

if (result.error) throw result.error;
process.exitCode = result.status ?? 1;
